# Generated by Django 3.0.5 on 2021-07-16 13:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='interest',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('All', 'All'), ('Technology', 'Tech'), ('Arts', 'Arts'), ('Fashion', 'Fashion'), ('Design', 'Design'), ('Politics', 'Politics'), ('Music', 'Music'), ('Drama', 'Drama'), ('Social', 'Social'), ('Meditation', 'Meditation'), ('Adventure', 'Adventure'), ('Comics', 'Comics'), ('Anime', 'Anime'), ('Novels', 'Novels'), ('Movie', 'Movie'), ('Religion', 'Religion'), ('Education', 'Education'), ('Transportation', 'Transportation'), ('Books', 'Books'), ('Science', 'Science'), ('Food', 'Food'), ('Nutrition', 'Nutrition'), ('Travel and Tour', 'Travel and Tour'), ('Space', 'Space'), ('Animals', 'Animals'), ('History', 'History'), ('Crypto_currency', 'Crypto_currency'), ('Health', 'Health'), ('INnovation', 'Innovation'), ('Crime', 'Crime'), ('Justice', 'Justice'), ('Comedy', 'Comedy'), ('Business', 'Business'), ('Fitness', 'Fitness'), ('Security', 'Security')], default='All', max_length=1000, null=True), size=None),
        ),
    ]
