# Generated by Django 3.0.5 on 2021-07-16 17:04

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20210716_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='interest',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('All', 'All'), ('Technology', 'Tech'), ('Arts', 'Arts'), ('Fashion', 'Fashion'), ('Design', 'Design'), ('Politics', 'Politics'), ('Music', 'Music'), ('Drama', 'Drama'), ('Social', 'Social'), ('Meditation', 'Meditation'), ('Adventure', 'Adventure'), ('Comics', 'Comics'), ('Anime', 'Anime'), ('Novels', 'Novels'), ('Movie', 'Movie'), ('Religion', 'Religion'), ('Education', 'Education'), ('Transportation', 'Transportation'), ('Books', 'Books'), ('Science', 'Science'), ('Food', 'Food'), ('Nutrition', 'Nutrition'), ('Travel and Tour', 'Travel and Tour'), ('Space', 'Space'), ('Animals', 'Animals'), ('History', 'History'), ('Crypto_currency', 'Crypto_currency'), ('Health', 'Health'), ('INnovation', 'Innovation'), ('Crime', 'Crime'), ('Justice', 'Justice'), ('Comedy', 'Comedy'), ('Business', 'Business'), ('Fitness', 'Fitness'), ('Security', 'Security')], max_length=291),
        ),
    ]
