# Generated by Django 3.1 on 2020-10-18 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20201016_0136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='profiles',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='users',
            new_name='user',
        ),
    ]
