# Generated by Django 3.1 on 2020-10-20 16:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0003_auto_20201018_2355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='profile',
            new_name='profiles',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='user',
            new_name='users',
        ),
        migrations.CreateModel(
            name='profiles_followed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='Myfollows',
            field=models.ManyToManyField(blank=True, related_name='profile_follows', through='profiles.profiles_followed', to=settings.AUTH_USER_MODEL),
        ),
    ]
