# Generated by Django 3.0.5 on 2021-05-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uuid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuids', models.CharField(max_length=225)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
