# Generated by Django 3.0.5 on 2021-06-26 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Uuid',
        ),
    ]
